// ────────────────────────────────────────────────────────────────────────────
// AI_PROJECT_INSTRUCTIONS.jsx — DEPRECATED
//
// ⚠ THIS FILE HAS BEEN SUPERSEDED.
//
// Agent instruction file renamed to: CHATGPT_INSTRUCTIONS.jsx
// Governance authority moved to:     BASE44_PROJECT_INSTRUCTIONS.jsx
//
// DO NOT use this file as governance authority.
// DO NOT use this file to define the canonical instruction set.
//
// Redirects:
//   • Agent preflight / instructions → CHATGPT_INSTRUCTIONS.jsx
//   • Governance rules, frozen files, data integrity → BASE44_PROJECT_INSTRUCTIONS.jsx
//   • Execution log → Phase25ExecutionLogIndex.jsx
//   • Next safe step → NextSafeStep.jsx
//
// Deprecated on: 2026-03-12 (Entry 97 — Audit System Hardening Pass)
// ────────────────────────────────────────────────────────────────────────────

export const PROJECT_INSTRUCTIONS = {
  
  // ──────────────────────────────────────────────────────────────────────────
  // AUDIT STORAGE RULE
  // ──────────────────────────────────────────────────────────────────────────
  
  AUDIT_STORAGE: {
    enabled: true,
    description: "All audits generated by AI must be persisted in the repository",
    
    directory: "src/audits/",
    
    rule: `
      All audits generated by AI must be persisted in the repository.
      
      Audit files must be stored in: src/audits/
      
      AI must never store audit results only in chat.
      
      If the directory does not exist, AI must create it.
      
      Filename format:
      - ui-audit-YYYY-MM-DD.md
      - architecture-audit-YYYY-MM-DD.md
      - governance-audit-YYYY-MM-DD.md
      
      Audit files must contain:
      • files inspected
      • current state summary
      • issues found (prioritized)
      • proposed cleanup passes (multiple options)
      • recommended action
      • governance safety confirmation
      
      Audit files are documentation only and must not contain code changes.
    `,
    
    auditTypes: [
      {
        name: "ui-audit",
        purpose: "User interface and visual consistency",
        frequency: "As needed for UI review",
        scope: [
          "Component styling",
          "Layout consistency",
          "Typography hierarchy",
          "Spacing and alignment",
          "Color usage",
          "Responsive design",
          "Icon consistency",
          "Visual redundancy"
        ]
      },
      {
        name: "architecture-audit",
        purpose: "Code structure and component design",
        frequency: "As needed for refactoring",
        scope: [
          "Component hierarchy",
          "Reusable component patterns",
          "Code duplication",
          "File organization",
          "Import dependencies",
          "Component responsibility"
        ]
      },
      {
        name: "governance-audit",
        purpose: "Project governance and process verification",
        frequency: "Ongoing during Phase 2.5+",
        scope: [
          "Execution log state",
          "Locked file integrity",
          "Governance rule compliance",
          "Chunk rollover readiness"
        ]
      }
    ],
    
    mandatoryPreflight: [
      "1. Read Phase25ExecutionLogIndex.jsx",
      "2. Read the active execution log chunk",
      "3. Read NextSafeStep.jsx",
      "4. Read this file (AI_PROJECT_INSTRUCTIONS.jsx)",
      "5. Run requested audit",
      "6. Store audit in src/audits/ before returning results"
    ]
  },

  // ──────────────────────────────────────────────────────────────────────────
  // GENERAL GOVERNANCE RULES
  // ──────────────────────────────────────────────────────────────────────────
  
  GOVERNANCE: {
    executionLogIndex: "components/governance/Phase25ExecutionLogIndex.jsx",
    nextSafeStep: "components/governance/NextSafeStep.jsx",
    lockedPhase2Files: [
      "functions/deleteAllGooglePlacesPrices",
      "functions/verifyGooglePlacesPriceNormalization",
      "functions/deleteGooglePlacesPricesForReclassification",
      "functions/classifyPricePlausibility",
      "functions/classifyStationsRuleEngine",
      "functions/classifyGooglePlacesConfidence"
    ],
    
    mandatoryReadOrder: [
      "1. Phase25ExecutionLogIndex.jsx (entry point)",
      "2. Active chunk file from Index (current work)",
      "3. NextSafeStep.jsx (approved action)",
      "4. AI_PROJECT_INSTRUCTIONS.jsx (this file)"
    ],
    
    forbiddenActions: [
      "Do not modify locked Phase 2 files",
      "Do not guess next step from log titles alone",
      "Do not implement without reading active chunk tail",
      "Do not bundle unrelated changes",
      "Do not override execution log with chat-only decisions"
    ]
  }
};

export default PROJECT_INSTRUCTIONS;