// ────────────────────────────────────────────────────────────────────────────
// CHATGPT_INSTRUCTIONS.jsx
//
// PURPOSE: Agent instruction reference for ChatGPT conversations with TankRadar.
//
// ⚠ THIS FILE IS NOT GOVERNANCE AUTHORITY.
// Governance authority lives in: BASE44_PROJECT_INSTRUCTIONS.jsx
//
// This file provides ChatGPT with:
//   • preflight read order
//   • audit storage rules
//   • frozen file list
//   • forbidden action list
//
// It does NOT override Phase25ExecutionLogIndex.jsx or BASE44_PROJECT_INSTRUCTIONS.jsx.
//
// Renamed from: AI_PROJECT_INSTRUCTIONS.jsx (deprecated)
// Renamed on:   2026-03-12 (Entry 97 — Audit System Hardening Pass)
// ────────────────────────────────────────────────────────────────────────────

export const CHATGPT_INSTRUCTIONS = {

  // ──────────────────────────────────────────────────────────────────────────
  // MANDATORY PREFLIGHT READ ORDER
  // ──────────────────────────────────────────────────────────────────────────

  mandatoryPreflight: [
    "1. Read components/governance/Phase25ExecutionLogIndex.jsx",
    "2. Read the ACTIVE chunk file referenced in Phase25ExecutionLogIndex.chunks[] (currently Phase25ExecutionLog_007.jsx)",
    "3. Read components/governance/NextSafeStep.jsx",
    "4. Read this file (CHATGPT_INSTRUCTIONS.jsx) — agent reference only",
    "5. Run requested audit or implementation",
    "6. Append execution log entry BEFORE returning results"
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // AUDIT STORAGE RULES
  // ──────────────────────────────────────────────────────────────────────────

  AUDIT_STORAGE: {
    enabled: true,
    description: "All audits generated by AI must be persisted in the repository",

    directory: "src/components/audits/",

    rule: `
      All audits generated by AI must be persisted in the repository.

      Audit files must be stored in: src/components/audits/{category}/

      AI must never store audit results only in chat.

      Filename format:
      - {topic}-{domain}-audit-YYYY-MM-DD.jsx

      Audit files must contain (per AUDIT_SYSTEM_GUIDE.jsx):
      • context
      • filesInspected
      • observedBehavior
      • confirmedFacts
      • structuralRisks
      • unknowns
      • recommendations

      Audit files are documentation only and must not contain code changes.

      All audits must be registered in: src/components/audits/AUDIT_INDEX.jsx
    `,

    categories: [
      "architecture",
      "ui",
      "governance",
      "product",
      "activation",
      "data",
      "performance",
      "security",
      "publishability"
    ],

    evidenceLevels: {
      "code-observed": "Directly visible in source code; requires no inference",
      "reasoned-inference": "Logical deduction from code patterns; not directly observed",
      "requires-telemetry": "Requires runtime metrics or user behavior data to verify",
      "user-experience-hypothesis": "Based on design principles or user testing assumptions"
    }
  },

  // ──────────────────────────────────────────────────────────────────────────
  // GOVERNANCE AUTHORITY
  // ──────────────────────────────────────────────────────────────────────────

  GOVERNANCE_AUTHORITY: {
    canonicalGovernanceFile: "components/governance/BASE44_PROJECT_INSTRUCTIONS.jsx",
    executionLogIndex: "components/governance/Phase25ExecutionLogIndex.jsx",
    nextSafeStep: "components/governance/NextSafeStep.jsx",
    agentInstructions: "components/governance/CHATGPT_INSTRUCTIONS.jsx (this file)",

    conflictResolution:
      "If this file conflicts with Phase25ExecutionLogIndex.jsx or BASE44_PROJECT_INSTRUCTIONS.jsx, " +
      "those files are authoritative. This file is a summary pointer only."
  },

  // ──────────────────────────────────────────────────────────────────────────
  // FROZEN PHASE-2 FILES — DO NOT MODIFY
  // ──────────────────────────────────────────────────────────────────────────

  lockedPhase2Files: [
    "functions/deleteAllGooglePlacesPrices",
    "functions/verifyGooglePlacesPriceNormalization",
    "functions/deleteGooglePlacesPricesForReclassification",
    "functions/classifyPricePlausibility",
    "functions/classifyStationsRuleEngine",
    "functions/classifyGooglePlacesConfidence"
  ],

  // ──────────────────────────────────────────────────────────────────────────
  // FORBIDDEN ACTIONS
  // ──────────────────────────────────────────────────────────────────────────

  forbiddenActions: [
    "Do not modify locked Phase 2 files under any circumstances",
    "Do not guess next step from execution log entry titles alone",
    "Do not implement without reading active chunk tail first",
    "Do not bundle unrelated changes into a single implementation step",
    "Do not override execution log decisions with chat-only state"
  ]
};

export default CHATGPT_INSTRUCTIONS;